apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  labels:
    app: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: docker.io/procof/board:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/boarddb
            - name: SPRING_DATASOURCE_USERNAME
              value: boarduser
            - name: SPRING_DATASOURCE_PASSWORD
              value: boardpass
