name: ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Docker Hub 로그인
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 이미지 빌드 & 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/board:${{ github.sha }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/board:latest

  update-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # manifest 브랜치 체크아웃 (없으면 생성)
      - name: Checkout manifest branch
        uses: actions/checkout@v4
        with:
          ref: manifest
          fetch-depth: 0

      - name: Ensure k8s folder exists
        run: mkdir -p k8s

      # yq 설치
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      # 이미지 태그 업데이트
      - name: Update image tag
        run: |
          yq e '.spec.template.spec.containers[0].image = "docker.io/${{ secrets.DOCKER_USERNAME }}/board:${{ github.sha }}"' -i k8s/deployment.yaml

      # Git commit & push
      - name: Commit & push changes
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@local"
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add k8s/deployment.yaml
            git commit -m "ci: image ${{ github.sha }}"
            git push origin manifest
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
