name: ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Docker Hub 로그인
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 이미지 빌드 & 푸시
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/board:${{ github.sha }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/board:latest

  update-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: manifest   # 매니페스트 브랜치 체크아웃

      # yq 설치
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      # 이미지 태그 업데이트
      - name: Update image tag
        run: |
          yq e '.spec.template.spec.containers[0].image = "docker.io/${{ secrets.DOCKER_USERNAME }}/board:${{ github.sha }}"' -i k8s/deployment.yaml

      # Git commit & push
      - name: Commit & push
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@local"
          git add k8s/deployment.yaml
          git commit -m "ci: image ${{ github.sha }}" || echo "No changes to commit"
          git push origin manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
