name: ci
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Docker Hub 로그인
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 이미지 빌드 & 푸시
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/board:${{ github.sha }}

  update-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: manifest          # 매니페스트 브랜치 체크아웃
      - name: Update image tag
        run: |
          yq e '.spec.template.spec.containers[0].image = "docker.io/${{ secrets.DOCKER_USERNAME }}/board:${{ github.sha }}"' -i k8s/deployment.yaml
      - name: Commit & push
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@local"
          git commit -am "ci: image ${{ github.sha }}"
          git push origin manifest
